name: Keep Alive
on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }} 
      - name: view files
        run: |
          cd .github/workflows
          ls -la
      - name: Commit and push workflow changes
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          # Set Git identity using GitHub Actions environment variables
          git config --global user.name "${{ secrets.GIT_USERNAME }}"
          git config --global user.email "${{ secrets.GIT_EMAIL }}"

          # Stage all changes (customize this if needed)
          # git add .github/workflows/Update.yml

          # Commit the changes
          git commit -m "Keep Alive"

          # Set the repository remote using the PAT token
          git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}.git

          # Push the changes to the repository
          git push origin main